version: '3.8'

services:
  db:
    image: mysql 
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: codigo_123
      MYSQL_DATABASE: led
      MYSQL_USER: led
      MYSQL_PASSWORD: codigo_123
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./:/usr/app

volumes:
  mysql_data:
